# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go


name: Deployment

on: 
  workflow_dispatch:
   inputs:
      VersionNumber:
        description: 'The New Version Number Ex: "1.2.3"'
        required: true
        type: string
        default: "0.0.0"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build Installer
      run: make

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: ./output/upload/

    - name: Create a release
      id: create_release
      run: |
        tag=$(echo "${GITHUB_REF#refs/tags/}")
        gh release create "$tag" ./output/release/* --title "$tag" --notes "Release $tag"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      run: |
        tag=$(echo "${GITHUB_REF#refs/tags/}")
        gh release upload "$tag" ./output/release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
